# Site settings
title: Programming divination
email: paulo.sigrist@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My 50 cents about programming.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sigrist,github.io" # the base hostname & protocol for your site
twitter_username: prsigrist
github_username:  sigrist

# Build settings
markdown: kramdown

# Theme settings
theme: jekyll-theme-hacker
